include(FindPackageHandleStandardArgs)
if(QWT_INCLUDE_DIR AND QWT_LIBRARIES)
   set(Qwt_FIND_QUIETLY TRUE)
endif(QWT_INCLUDE_DIR AND QWT_LIBRARIES)
find_path(QWT_INCLUDE_DIR qwt.h HINTS  /usr/local/qwt-6.0.2-svn/include/ /usr/local/qwt-6.0.2/include/ /usr/include/qwt)
find_library(QWT_LIBRARIES libqwt.so HINTS /usr/local/qwt-6.0.2-svn/lib/ /usr/local/qwt-6.0.2/lib/ /usr/lib/)
message(QWT_INCLUDE_DIR=${QWT_INCLUDE_DIR} QWT_LIBRARIES=${QWT_LIBRARIES})
find_package_handle_standard_args(Qwt DEFAULT_MSG QWT_LIBRARIES QWT_INCLUDE_DIR)
mark_as_advanced(QWT_LIBRARIES)
