#include(FindPackageHandleStandardArgs)
if(LIB_LINTER_INCLUDE_DIR AND LIB_LINTER_LIBRARIES)
   set(LibLinter_FIND_QUIETLY TRUE)
   endif(LIB_LINTER_INCLUDE_DIR AND LIB_LINTER_LIBRARIES)
   
   find_path(LIB_LINTER_INCLUDE_DIR inter.h HINTS  /usr/linter/intlib/)
   find_path(LIB_LINTER_INCLUDE_EXLIB exlib.h HINTS  /usr/linter/samples/call/exlib/)
   find_file(LIB_LINTER_LIBRARIES libintlib.a HINTS /usr/linter/intlib/)
   find_file(LIB_LINTER_LIBRARIES_EXLIB exlib.a HINTS /usr/linter/samples/call/exlib/)
#   find_package_handle_standard_args(LibLinter DEFAULT_MSG LIB_LINTER_LIBRARIES LIB_LINTER_INCLUDE_DIR)
   mark_as_advanced(LIB_LINTER_LIBRARIES)
   mark_as_advanced(LIB_LINTER_LIBRARIES_EXLIB)