MACRO(include_our_libqwt)
   message("Check libqwt")
   find_path(QWT_INCLUDE_DIR qwt.h HINTS ${CMAKE_SOURCE_DIR}/src_lib/libqwt612/src/ )
   find_library(QWT_LIBRARIES NAMES libqwt.so PATHS ${LIBRARY_OUTPUT_PATH})
   message(QWT_INCLUDE_DIR=${QWT_INCLUDE_DIR})
   message(QWT_LIBRARIES=${QWT_LIBRARIES})
   if(${QWT_INCLUDE_DIR} STREQUAL "QWT_INCLUDE_DIR-NOTFOUND")
      message("Check libqwt ... NOT FOUND")
   else(${QWT_INCLUDE_DIR} STREQUAL "QWT_INCLUDE_DIR-NOTFOUND")
      message("Check libqwt ... OK")
   endif(${QWT_INCLUDE_DIR} STREQUAL "QWT_INCLUDE_DIR-NOTFOUND")
   include_directories(${QWT_INCLUDE_DIR})
ENDMACRO(include_our_libqwt)
