MACRO(include_our_lib_snmp)
   message("Check libsnmp++")
   message(CMAKE_SOURCE_DIR = ${CMAKE_SOURCE_DIR})
   message(LIBRARY_OUTPUT_PATH=${LIBRARY_OUTPUT_PATH})
   find_path( LIB_SNMP_INCLUDE_DIR snmp_pp HINTS ${CMAKE_SOURCE_DIR}/src_lib/libsnmp/include )
   find_library(LIB_SNMP_LIBRARIES NAMES snmp++ PATHS ${LIBRARY_OUTPUT_PATH})
   message(LIB_SNMP_INCLUDE_DIR=${LIB_SNMP_INCLUDE_DIR})
   message(LIB_SNMP_LIBRARIES  =${LIB_SNMP_LIBRARIES})
   if(${LIB_SNMP_INCLUDE_DIR} STREQUAL "LIB_SNMP_INCLUDE_DIR-NOTFOUND")
      message("Check libsnmp++ ... NOT FOUND")
   else(${LIB_SNMP_INCLUDE_DIR} STREQUAL "LIB_SNMP_INCLUDE_DIR-NOTFOUND")
      message("Check libsnmp++ ... OK")
   endif(${LIB_SNMP_INCLUDE_DIR} STREQUAL "LIB_SNMP_INCLUDE_DIR-NOTFOUND")
   include_directories(${LIB_SNMP_INCLUDE_DIR})
ENDMACRO(include_our_lib_snmp)